### ISSUE TITLE
Cannot autoswap

### ISSUE THREAD

**Issue by ghost** [themeliolabs/melwalletd#16]
## Details

As the title says, it is not possible to use melwallet-cli for autoswap, I think this is a melwalletd issue, so I am post the issue in this repo.

![image](https://user-images.githubusercontent.com/95868829/222498864-6b378f59-a9a1-4e2b-b26f-c77be8d71736.png)

## Other information

Environment information:

- OS: Debian 11.6 amd64
- Kernel: `#1 SMP Debian 5.10.162-1 (2023-01-21)`
- CPU: Ryzen 5 3600
- RAM: 64 GB
- Disk: Three 500 GB NVMe SSDs in RAID 0
- melawlletd version: 0.6.2
- melwallet-cli version: 0.7.2
- melwalletd command: `melwalletd --wallet-dir .swap-wallets -l 127.0.0.1:21773`
- melwallet-cli command: `melwallet-cli autoswap -w <Wallet_name> 100000 --endpoint=127.0.0.1:21773`

**Comment by nullchinchilla** [comment]
This has been fixed in 0.7.3.
